# Generated by Django 4.2.17 on 2025-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_devicevideo_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgrokURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtmp_url', models.CharField(blank=True, max_length=200, null=True)),
                ('hls_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
